version: 2
updates:
  - package-ecosystem: nuget
    directory: "/"
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
    groups:
      astronomy-deps:
        patterns:
          - "*"
        exclude-patterns:
          - "CosineKitty.AstronomyEngine"
          - "One_Sgp4"
      astronomy-engines:
        patterns:
          - "CosineKitty.AstronomyEngine"
          - "One_Sgp4"
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      day: sunday
    open-pull-requests-limit: 3
    groups:
      github-actions:
        patterns:
          - "*"
