<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CosineKitty.AstronomyEngine" Version="2.1.19" />
    <PackageReference Include="Microsoft.Data.Sqlite" Version="10.0.10" />
    <PackageReference Include="SQLitePCLRaw.bundle_e_sqlite3" Version="3.0.5" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Astronomy.Infrastructure\Astronomy.Infrastructure.csproj" />
    <ProjectReference Include="..\Astronomy.Modules.Ephemeris\Astronomy.Modules.Ephemeris.csproj" />
    <ProjectReference Include="..\Astronomy.Modules.Satellites\Astronomy.Modules.Satellites.csproj" />
    <ProjectReference Include="..\Astronomy.SharedKernel\Astronomy.SharedKernel.csproj" />
  </ItemGroup>

</Project>
