// <auto-generated />
using Astronomy.Modules.Satellites.Application;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Astronomy.Modules.Satellites.Migrations
{
    [DbContext(typeof(SatelliteDbContext))]
    [Migration("20260804182416_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("Astronomy.Modules.Satellites.Application.SatelliteElementRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DatasetVersion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ElementsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EpochUtc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NoradId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ObjectName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DatasetVersion", "NoradId");

                    b.ToTable("Elements");
                });
#pragma warning restore 612, 618
        }
    }
}
